# Generated by Django 3.2.5 on 2022-06-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('post', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
    ]
