# Generated by Django 3.2.5 on 2022-07-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_informations'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='address2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='informations',
            name='address1',
            field=models.CharField(max_length=500),
        ),
    ]
