# Generated by Django 3.2.5 on 2022-07-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_offeredservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offeredservices',
            old_name='sesrvice_icon',
            new_name='service_icon',
        ),
    ]
